# Generated by Django 5.2 on 2025-04-17 17:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookmodule', '0004_card1_course1_department1_students1'),
    ]

    operations = [
        migrations.CreateModel(
            name='Card11',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('card_number', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Course11',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('code', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Department11',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Students11',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('card', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='bookmodule.card11')),
                ('course', models.ManyToManyField(to='bookmodule.course11')),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bookmodule.department11')),
            ],
        ),
        migrations.RemoveField(
            model_name='students1',
            name='card',
        ),
        migrations.RemoveField(
            model_name='student1',
            name='card',
        ),
        migrations.DeleteModel(
            name='Card1',
        ),
        migrations.RemoveField(
            model_name='student1',
            name='courses',
        ),
        migrations.RemoveField(
            model_name='students1',
            name='course',
        ),
        migrations.DeleteModel(
            name='Course1',
        ),
        migrations.RemoveField(
            model_name='student1',
            name='department',
        ),
        migrations.RemoveField(
            model_name='students1',
            name='department',
        ),
        migrations.DeleteModel(
            name='Department1',
        ),
        migrations.DeleteModel(
            name='Card',
        ),
        migrations.DeleteModel(
            name='Course',
        ),
        migrations.DeleteModel(
            name='Student1',
        ),
        migrations.DeleteModel(
            name='Department',
        ),
        migrations.DeleteModel(
            name='Students1',
        ),
    ]
