# Generated by Django 5.2 on 2025-04-26 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookmodule', '0005_card11_course11_department11_students11_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Book3',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('author', models.CharField(max_length=50)),
                ('price', models.FloatField(default=0.0)),
                ('edition', models.SmallIntegerField(default=1)),
            ],
        ),
    ]
