# Generated by Django 5.2 on 2025-04-27 18:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookmodule', '0009_profile'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Profile',
            new_name='Profile2',
        ),
    ]
